//
// PricingAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class PricingAPI {
    
    open class func postPublicApiPricingGerenate(body: ApiPricingsBody? = nil, completion: @escaping ((_ data: PriceResult?,_ error: Error?) -> Void)) {
        postPublicApiPricingGerenateWithRequestBuilder(body: body).execute { (response, error) -> Void in
            if error == nil {
                completion(response?.body, error)
            } else {
                completion(nil, error)
            }
        }
    }

    open class func postPublicApiPricingGerenateWithRequestBuilder(body: ApiPricingsBody? = nil) -> RequestBuilder<PriceResult> {
        let path = "/public/api/pricings"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<PriceResult>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
}
